language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required

jobs:
  include:
  - name: "run basic tests with python 3.5.1"
    dist: trusty
    python: 3.5.1
    script: |
      set -e
      pytest
  - name: "run test suite with python 3.6"
    python: 3.6
    script: |
      set -e
      pytest
  - name: "run test suite with python 3.7"
    python: 3.7
    script: |
      set -e
      pytest


before_install: |
  # Upgrade pip, setuptools, and wheel
  pip install -U pip setuptools wheel

install: |
  pip install -Ur external/mypy/test-requirements.txt
  pip install -U .
  export PYTHONPATH=`pwd`/external/mypy
